server:
  port: 8060
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zos?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 01Studio
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
  application:
    name: resource
  redis:
    pool:
      max-active: 1024
      max-idle: 200
      max-wait: 1000
    timeout: 5000
    host: localhost
    port: 6379
  data:
    rest:
      page-param-name: page
      sort-param-name: sort
      enable-enum-translation: true
      default-page-size: 1024
      max-page-size: 1024
zos:
  security:
    oauth2:
      tokenStore: redis
    swagger:
      enable: true
      token: ""
logging:
  file: logs/${spring.application.name}