server:
  port: 8070
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zos?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 01Studio
zos:
  security:
    oauth2:
      clients: [
        {clientId: xxx, clientSecret: xxx},
        {clientId: zos, clientSecret: zos},
        {clientId: 01Studio, clientSecret: 01Studio}
      ]
      tokenStore: redis